/**
 * Pull Request Workflow UI
 *
 * Provides user confirmation and review steps before pushing tokens to GitHub.
 * Implements a 3-step workflow: Preview → Commit Details → Success
 */

import { ExtractionResult } from '../TokenExtractor';

// =============================================================================
// TYPES
// =============================================================================

export interface PRWorkflowOptions {
  tokenData: ExtractionResult;
  defaultBranch?: string;
  onComplete: (details: PRDetails) => void;
  onCancel: () => void;
}

export interface PRDetails {
  action: 'push-to-branch' | 'create-pr';
  branchName: string;
  commitMessage: string;
  prTitle?: string;
  prBody?: string;
  isNewBranch: boolean;
}

export interface PRSuccess {
  prNumber?: number;
  prUrl?: string;
  branchName: string;
  action: 'push-to-branch' | 'create-pr';
}

// =============================================================================
// PR WORKFLOW UI
// =============================================================================

export class PRWorkflowUI {
  private options: PRWorkflowOptions;
  private currentStep: 'preview' | 'details' | 'success' = 'preview';
  private prDetails: Partial<PRDetails> = {};

  constructor(options: PRWorkflowOptions) {
    this.options = options;
    this.initializePRDetails();
  }

  /**
   * Show the PR workflow starting with preview
   */
  show(): void {
    this.showPreviewModal();
    this.setupMessageHandling();
  }

  /**
   * Show success modal after PR creation
   */
  showSuccess(success: PRSuccess): void {
    this.currentStep = 'success';
    this.showSuccessModal(success);
  }

  // =============================================================================
  // INITIALIZATION
  // =============================================================================

  /**
   * Initialize PR details with defaults
   */
  private initializePRDetails(): void {
    const timestamp = new Date().toISOString()
      .replace(/:/g, '-')
      .replace(/\..+/, '')
      .replace('T', '-');

    this.prDetails = {
      action: 'create-pr',
      branchName: `tokens/update-${timestamp}`,
      commitMessage: 'Update design tokens from Figma',
      prTitle: `Update design tokens - ${new Date().toLocaleDateString()}`,
      prBody: this.generatePRBody(),
      isNewBranch: true
    };
  }

  /**
   * Generate PR body markdown
   */
  private generatePRBody(): string {
    const { tokenData } = this.options;
    const timestamp = new Date().toISOString();
    const date = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    return `## Design Token Update

**Exported from Figma**: ${tokenData.metadata.documentName || 'Figma Document'}
**Date**: ${date}
**Total tokens**: ${tokenData.tokens.length}
**Total variables**: ${tokenData.variables.length}
**Collections**: ${tokenData.collections.length}

### File Changes
- \`tokens/raw/figma-tokens.json\`

### Token Summary
- **Design Tokens**: ${tokenData.tokens.length} tokens
- **Variables**: ${tokenData.variables.length} variables
- **Collections**: ${tokenData.collections.length} collections

### Review Checklist
- [ ] Token values are correct
- [ ] No breaking changes to token names
- [ ] Ready to merge

---
🤖 Generated by Figma Design System Distributor
*Timestamp: ${timestamp}*`;
  }

  // =============================================================================
  // STEP 1: PREVIEW MODAL
  // =============================================================================

  /**
   * Show preview modal with token summary
   */
  private showPreviewModal(): void {
    const { tokenData } = this.options;
    const fileSize = this.estimateFileSize(tokenData);

    const html = `
<!DOCTYPE html>
<html>
<head>
  ${this.getSharedStyles()}
  <style>
    .preview-stats {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 16px;
      margin: 24px 0;
    }

    .stat-card {
      background: #f8f9fa;
      border-radius: 8px;
      padding: 16px;
      text-align: center;
    }

    .stat-value {
      font-size: 32px;
      font-weight: 600;
      color: #667eea;
      margin-bottom: 4px;
    }

    .stat-label {
      font-size: 12px;
      color: #666;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }

    .collection-list {
      margin: 16px 0;
      padding: 16px;
      background: #f8f9fa;
      border-radius: 8px;
    }

    .collection-item {
      padding: 8px 0;
      border-bottom: 1px solid #e9ecef;
    }

    .collection-item:last-child {
      border-bottom: none;
    }

    .collection-name {
      font-weight: 500;
      color: #333;
    }

    .info-box {
      background: #e7f3ff;
      border-left: 4px solid #667eea;
      padding: 12px 16px;
      margin: 16px 0;
      border-radius: 4px;
    }

    .info-box-title {
      font-weight: 600;
      color: #333;
      margin-bottom: 4px;
    }

    .info-box-text {
      font-size: 13px;
      color: #666;
      line-height: 1.5;
    }
  </style>
</head>
<body>
  <div class="modal-container">
    <div class="modal-header">
      <h1>🎨 Design Tokens Ready</h1>
      <p>Review the extracted tokens before creating a pull request</p>
    </div>

    <div class="modal-content">
      <div class="preview-stats">
        <div class="stat-card">
          <div class="stat-value">${tokenData.tokens.length}</div>
          <div class="stat-label">Design Tokens</div>
        </div>
        <div class="stat-card">
          <div class="stat-value">${tokenData.variables.length}</div>
          <div class="stat-label">Variables</div>
        </div>
        <div class="stat-card">
          <div class="stat-value">${tokenData.collections.length}</div>
          <div class="stat-label">Collections</div>
        </div>
        <div class="stat-card">
          <div class="stat-value">${fileSize}</div>
          <div class="stat-label">File Size</div>
        </div>
      </div>

      ${tokenData.collections.length > 0 ? `
        <div class="collection-list">
          <h3 style="margin: 0 0 12px 0; font-size: 14px; color: #333;">Collections</h3>
          ${tokenData.collections.map(col => `
            <div class="collection-item">
              <span class="collection-name">${col.name}</span>
            </div>
          `).join('')}
        </div>
      ` : ''}

      <div class="info-box">
        <div class="info-box-title">📝 Next Step: Create Pull Request</div>
        <div class="info-box-text">
          Clicking "Review & Push" will let you customize the commit message and PR title
          before creating a pull request. No changes will be made to your repository until you confirm.
        </div>
      </div>
    </div>

    <div class="modal-actions">
      <button class="btn btn-secondary" onclick="handleCancel()">Cancel</button>
      <button class="btn btn-primary" onclick="handleNext()">Review & Push</button>
    </div>
  </div>

  <script>
    function handleCancel() {
      parent.postMessage({ pluginMessage: { type: 'pr-workflow-cancel' } }, '*');
    }

    function handleNext() {
      parent.postMessage({ pluginMessage: { type: 'pr-workflow-next', step: 'preview' } }, '*');
    }
  </script>
</body>
</html>`;

    figma.showUI(html, { width: 500, height: 600, themeColors: true });
  }

  // =============================================================================
  // STEP 2: COMMIT DETAILS FORM
  // =============================================================================

  /**
   * Show commit details form
   */
  private showDetailsModal(): void {
    const details = this.prDetails;

    const html = `
<!DOCTYPE html>
<html>
<head>
  ${this.getSharedStyles()}
  <style>
    .form-group {
      margin-bottom: 20px;
    }

    .form-label {
      display: block;
      font-weight: 500;
      color: #333;
      margin-bottom: 8px;
      font-size: 14px;
    }

    .form-input, .form-textarea {
      width: 100%;
      padding: 12px;
      border: 2px solid #e9ecef;
      border-radius: 8px;
      font-size: 14px;
      font-family: inherit;
      transition: border-color 0.3s ease;
    }

    .form-input:focus, .form-textarea:focus {
      outline: none;
      border-color: #667eea;
    }

    .form-textarea {
      resize: vertical;
      min-height: 100px;
      font-family: inherit;
    }

    .form-help {
      font-size: 12px;
      color: #666;
      margin-top: 4px;
    }

    .form-input[readonly] {
      background: #f8f9fa;
      color: #666;
      cursor: not-allowed;
    }

    .section-title {
      font-size: 16px;
      font-weight: 600;
      color: #333;
      margin: 24px 0 16px 0;
      padding-bottom: 8px;
      border-bottom: 2px solid #e9ecef;
    }
  </style>
</head>
<body>
  <div class="modal-container">
    <div class="modal-header">
      <h1>📝 Pull Request Details</h1>
      <p>Customize the commit message and PR title</p>
    </div>

    <div class="modal-content">
      <h2 class="section-title">Branch Information</h2>

      <div class="form-group">
        <label class="form-label">Branch Name</label>
        <input
          type="text"
          class="form-input"
          id="branch-name"
          value="${details.branchName}"
          readonly
        >
        <div class="form-help">Auto-generated branch name (read-only)</div>
      </div>

      <h2 class="section-title">Commit Details</h2>

      <div class="form-group">
        <label class="form-label">Commit Message</label>
        <textarea
          class="form-textarea"
          id="commit-message"
          placeholder="Update design tokens from Figma"
        >${details.commitMessage}</textarea>
        <div class="form-help">Describe the token changes (supports multiple lines)</div>
      </div>

      <h2 class="section-title">Pull Request Details</h2>

      <div class="form-group">
        <label class="form-label">PR Title</label>
        <input
          type="text"
          class="form-input"
          id="pr-title"
          value="${details.prTitle}"
          placeholder="Update design tokens - ${new Date().toLocaleDateString()}"
        >
        <div class="form-help">Title that will appear on GitHub</div>
      </div>
    </div>

    <div class="modal-actions">
      <button class="btn btn-secondary" onclick="handleBack()">Back</button>
      <button class="btn btn-primary" onclick="handleCreatePR()">Create Pull Request</button>
    </div>
  </div>

  <script>
    function handleBack() {
      parent.postMessage({ pluginMessage: { type: 'pr-workflow-back' } }, '*');
    }

    function handleCreatePR() {
      const details = {
        branchName: document.getElementById('branch-name').value,
        commitMessage: document.getElementById('commit-message').value,
        prTitle: document.getElementById('pr-title').value
      };

      parent.postMessage({
        pluginMessage: {
          type: 'pr-workflow-create',
          details
        }
      }, '*');
    }

    // Auto-save on input
    document.getElementById('commit-message').addEventListener('input', (e) => {
      parent.postMessage({
        pluginMessage: {
          type: 'pr-workflow-update',
          field: 'commitMessage',
          value: e.target.value
        }
      }, '*');
    });

    document.getElementById('pr-title').addEventListener('input', (e) => {
      parent.postMessage({
        pluginMessage: {
          type: 'pr-workflow-update',
          field: 'prTitle',
          value: e.target.value
        }
      }, '*');
    });
  </script>
</body>
</html>`;

    figma.showUI(html, { width: 500, height: 650, themeColors: true });
  }

  // =============================================================================
  // STEP 3: SUCCESS MODAL
  // =============================================================================

  /**
   * Show success modal with PR link
   */
  private showSuccessModal(success: PRSuccess): void {
    const isPR = success.action === 'create-pr';
    const html = `
<!DOCTYPE html>
<html>
<head>
  ${this.getSharedStyles()}
  <style>
    .success-icon {
      font-size: 64px;
      text-align: center;
      margin: 24px 0;
    }

    .success-title {
      font-size: 24px;
      font-weight: 600;
      color: #28a745;
      text-align: center;
      margin-bottom: 8px;
    }

    .success-subtitle {
      text-align: center;
      color: #666;
      margin-bottom: 32px;
    }

    .pr-details {
      background: #f8f9fa;
      border-radius: 8px;
      padding: 20px;
      margin: 24px 0;
    }

    .pr-detail-row {
      display: flex;
      justify-content: space-between;
      padding: 12px 0;
      border-bottom: 1px solid #e9ecef;
    }

    .pr-detail-row:last-child {
      border-bottom: none;
    }

    .pr-detail-label {
      font-weight: 500;
      color: #666;
    }

    .pr-detail-value {
      font-weight: 600;
      color: #333;
    }

    .pr-link {
      display: block;
      background: #667eea;
      color: white;
      text-decoration: none;
      padding: 16px;
      border-radius: 8px;
      text-align: center;
      font-weight: 500;
      margin: 16px 0;
      transition: background 0.3s ease;
    }

    .pr-link:hover {
      background: #5a6fd8;
    }

    .next-steps {
      background: #e7f3ff;
      border-left: 4px solid #667eea;
      padding: 16px;
      margin: 24px 0;
      border-radius: 4px;
    }

    .next-steps-title {
      font-weight: 600;
      color: #333;
      margin-bottom: 8px;
    }

    .next-steps-list {
      font-size: 13px;
      color: #666;
      line-height: 1.8;
      margin-left: 20px;
    }
  </style>
</head>
<body>
  <div class="modal-container">
    <div class="modal-content">
      <div class="success-icon">✅</div>
      <h1 class="success-title">${isPR ? 'Pull Request Created!' : 'Pushed to Branch!'}</h1>
      <p class="success-subtitle">${isPR ? 'Your design tokens are ready for review' : 'Your tokens have been committed'}</p>

      <div class="pr-details">
        ${isPR && success.prNumber ? `
          <div class="pr-detail-row">
            <span class="pr-detail-label">PR Number</span>
            <span class="pr-detail-value">#${success.prNumber}</span>
          </div>
        ` : ''}
        <div class="pr-detail-row">
          <span class="pr-detail-label">Branch</span>
          <span class="pr-detail-value">${success.branchName}</span>
        </div>
      </div>

      ${success.prUrl ? `
        <a href="${success.prUrl}" class="pr-link" target="_blank">
          🔗 View ${isPR ? 'Pull Request' : 'Branch'} on GitHub
        </a>
      ` : ''}

      <div class="next-steps">
        <div class="next-steps-title">📋 Next Steps</div>
        <ul class="next-steps-list">
          <li>Review the token changes in the pull request</li>
          <li>Request review from team members if needed</li>
          <li>Merge the PR when ready to apply changes</li>
          <li>Tokens will be updated in the main branch after merge</li>
        </ul>
      </div>
    </div>

    <div class="modal-actions">
      <button class="btn btn-primary" onclick="handleDone()" style="width: 100%;">
        Done
      </button>
    </div>
  </div>

  <script>
    function handleDone() {
      parent.postMessage({ pluginMessage: { type: 'pr-workflow-done' } }, '*');
    }
  </script>
</body>
</html>`;

    figma.showUI(html, { width: 500, height: 600, themeColors: true });
  }

  // =============================================================================
  // MESSAGE HANDLING
  // =============================================================================

  /**
   * Setup message handling from UI
   */
  private setupMessageHandling(): void {
    figma.ui.onmessage = async (msg) => {
      switch (msg.type) {
        case 'pr-workflow-cancel':
          this.options.onCancel();
          break;

        case 'pr-workflow-next':
          if (msg.step === 'preview') {
            this.currentStep = 'details';
            this.showDetailsModal();
          }
          break;

        case 'pr-workflow-back':
          this.currentStep = 'preview';
          this.showPreviewModal();
          break;

        case 'pr-workflow-update':
          this.prDetails[msg.field as keyof PRDetails] = msg.value;
          break;

        case 'pr-workflow-create':
          // Update details with user input
          this.prDetails = {
            ...this.prDetails,
            ...msg.details,
            prBody: this.generatePRBody() // Always regenerate body with latest data
          };
          this.options.onComplete(this.prDetails as PRDetails);
          break;

        case 'pr-workflow-done':
          figma.closePlugin();
          break;
      }
    };
  }

  // =============================================================================
  // UTILITY METHODS
  // =============================================================================

  /**
   * Estimate file size from token data
   * Uses custom UTF-8 byte counting for Figma plugin environment
   */
  private estimateFileSize(tokenData: ExtractionResult): string {
    const jsonString = JSON.stringify(tokenData, null, 2);

    // Calculate UTF-8 byte length (Blob/TextEncoder not available in Figma)
    let bytes = 0;
    for (let i = 0; i < jsonString.length; i++) {
      const code = jsonString.charCodeAt(i);
      if (code < 0x80) {
        bytes += 1;
      } else if (code < 0x800) {
        bytes += 2;
      } else if ((code & 0xFC00) === 0xD800) {
        bytes += 4;
        i++; // Skip low surrogate
      } else {
        bytes += 3;
      }
    }

    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  }

  /**
   * Get shared CSS styles
   */
  private getSharedStyles(): string {
    return `
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }

        body {
          font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          padding: 20px;
          min-height: 100vh;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .modal-container {
          background: white;
          border-radius: 16px;
          box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);
          width: 100%;
          overflow: hidden;
          display: flex;
          flex-direction: column;
          max-height: 90vh;
        }

        .modal-header {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          padding: 24px;
          text-align: center;
        }

        .modal-header h1 {
          font-size: 24px;
          font-weight: 600;
          margin-bottom: 8px;
        }

        .modal-header p {
          font-size: 14px;
          opacity: 0.9;
        }

        .modal-content {
          padding: 24px;
          overflow-y: auto;
          flex: 1;
        }

        .modal-actions {
          display: flex;
          gap: 12px;
          padding: 20px 24px;
          background: #f8f9fa;
          border-top: 1px solid #e9ecef;
        }

        .btn {
          flex: 1;
          padding: 12px 24px;
          border: none;
          border-radius: 8px;
          font-weight: 500;
          font-size: 14px;
          cursor: pointer;
          transition: all 0.3s ease;
        }

        .btn-secondary {
          background: #6c757d;
          color: white;
        }

        .btn-secondary:hover {
          background: #5a6268;
        }

        .btn-primary {
          background: #667eea;
          color: white;
        }

        .btn-primary:hover {
          background: #5a6fd8;
        }
      </style>
    `;
  }
}
