/**
 * Pull Request Workflow UI
 *
 * Single-step workflow for pushing tokens to GitHub.
 * User can choose: Push to Branch OR Create Pull Request
 */

import { ExtractionResult } from '../TokenExtractor';
import { getWindowOptions } from './constants';
import { WorkflowTriggerConfig, WorkflowTriggerResult } from '../github/GitHubTypes';
import { SecureStorage, WorkflowSettings } from '../storage/SecureStorage';
import { generateDesignSystemCSS } from '../design-system/html-utils';
import { generateSmartCommitMessage } from '../main';
import { DocumentInfo } from '../types/CommonTypes';

// =============================================================================
// TYPES
// =============================================================================

export interface PRWorkflowOptions {
  tokenData: ExtractionResult;
  documentInfo: DocumentInfo;
  defaultBranch?: string;
  availableBranches?: string[];
  onComplete: (details: PRDetails) => void;
  onCancel: () => void;
}

export interface PRDetails {
  action: 'push-to-branch' | 'create-pr';
  branchName: string;
  commitMessage: string;
  prTitle?: string;
  prBody?: string;
  isNewBranch: boolean;
  tokenFileLocation?: string;  // NEW: Optional token file location
  workflowTrigger?: WorkflowTriggerConfig;  // NEW: Optional workflow trigger config
}

export interface PRSuccess {
  prNumber?: number;
  prUrl?: string;
  branchName: string;
  action: 'push-to-branch' | 'create-pr';
  workflowTrigger?: WorkflowTriggerResult;  // NEW: Workflow trigger result
}

// =============================================================================
// PR WORKFLOW UI
// =============================================================================

export class PRWorkflowUI {
  private options: PRWorkflowOptions;
  private prDetails: Partial<PRDetails> = {};

  constructor(options: PRWorkflowOptions) {
    this.options = options;
    this.initializePRDetails();
  }

  /**
   * Show the unified workflow
   */
  async show(): Promise<void> {
    await this.showUnifiedModal();
    this.setupMessageHandling();
  }

  /**
   * Show success modal after operation
   */
  showSuccess(success: PRSuccess): void {
    this.showSuccessModal(success);
  }

  // =============================================================================
  // INITIALIZATION
  // =============================================================================

  /**
   * Initialize PR details with defaults
   */
  private initializePRDetails(): void {
    const timestamp = new Date().toISOString()
      .replace(/:/g, '-')
      .replace(/\..+/, '')
      .replace('T', '-');

    // Generate smart commit message with token metadata
    const smartCommitMessage = generateSmartCommitMessage(
      this.options.tokenData,
      this.options.documentInfo
    );

    this.prDetails = {
      action: 'create-pr',
      branchName: `tokens/update-${timestamp}`,
      commitMessage: smartCommitMessage,
      prTitle: `Update design tokens - ${new Date().toLocaleDateString()}`,
      prBody: this.generatePRBody(),
      isNewBranch: true
    };
  }

  /**
   * Generate PR body markdown
   */
  private generatePRBody(): string {
    const { tokenData } = this.options;
    const date = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    return `## Design Token Update

**Exported from Figma**: ${tokenData.metadata.documentName || 'Figma Document'}
**Date**: ${date}

### File Changes
- \`tokens/raw/figma-tokens.json\`

### Review Checklist
- [ ] Token values are correct
- [ ] No breaking changes to token names
- [ ] Ready to merge

---
🤖 Generated by Token Launch`;
  }

  // =============================================================================
  // UNIFIED MODAL
  // =============================================================================

  /**
   * Show unified single-step modal
   */
  private async showUnifiedModal(): Promise<void> {
    const { tokenData } = this.options;
    const collections = tokenData.collections || [];
    const defaultBranch = this.options.defaultBranch || 'main';

    // Load saved workflow settings
    const workflowSettings = await SecureStorage.getWorkflowSettings() || {
      workflowTriggerEnabled: false,
      workflowFileName: 'transform-tokens.yml'
    };

    // Get saved token file location (with fallback to default)
    const getSavedTokenFileLocation = (): string => {
      try {
        return localStorage.getItem('tokenFileLocation') || '/tokens';
      } catch (e) {
        return '/tokens'; // Fallback if localStorage unavailable
      }
    };
    const savedTokenFileLocation = getSavedTokenFileLocation();

    const html = `
<!DOCTYPE html>
<html>
<head>
  <link href="https://unpkg.com/phosphor-icons@1.4.2/src/css/icons.css" rel="stylesheet">
  ${this.getSharedStyles()}
  <style>
    body {
      margin: 0;
      padding: 0 24px;
      overflow-y: auto;
      overflow-x: hidden;
      font-family: var(--font-family);
      background: var(--color-background-gradient) !important;
      min-height: 100vh;
    }

    .container {
      min-height: 100vh;
      height: auto;
      display: flex;
      flex-direction: column;
      background: white;
      border-radius: 16px;
      box-shadow: var(--shadow-xl);
    }

    .header {
      background: var(--color-background-gradient, linear-gradient(135deg, #DEE3FC 0%, #F7E3E3 100%));
      color: #000000;
      padding: 16px 20px;
      flex-shrink: 0;
      text-align: center;
    }

    .header h1 {
      font-size: 18px;
      font-weight: 600;
      margin: 0;
    }

    .content {
      flex: 1;
      overflow: visible;
      padding: 20px 20px 10px 20px;
    }

    /* Compact Stats */
    .stats {
      display: flex;
      gap: 12px;
      margin-bottom: 20px;
    }

    .stat {
      flex: 1;
      background: #f8f9fa;
      padding: 10px;
      border-radius: 6px;
      text-align: center;
    }

    .stat-value {
      font-size: 20px;
      font-weight: 600;
      color: #000000;
      margin-bottom: 2px;
    }

    .stat-label {
      font-size: 11px;
      color: #666;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }

    /* Collections - Collapsed by Default */
    .collections {
      margin-bottom: 20px;
    }

    .collections-toggle {
      display: flex;
      align-items: center;
      gap: 6px;
      padding: 8px;
      cursor: pointer;
      user-select: none;
      border-radius: 4px;
      transition: background 0.2s;
    }

    .collections-toggle:hover {
      background: var(--color-background-secondary);
    }

    .toggle-icon {
      font-size: 10px;
      transition: transform 0.3s;
    }

    .toggle-icon.open {
      transform: rotate(90deg);
    }

    .toggle-text {
      font-size: 11px;
      color: #666;
    }

    .collections-list {
      max-height: 0;
      overflow: hidden;
      transition: max-height 0.3s ease;
    }

    .collections-list.open {
      max-height: 150px;
      overflow-y: auto;
      margin-top: 8px;
    }

    .collection-item {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 6px 10px;
      background: #f8f9fa;
      border-radius: 4px;
      margin-bottom: 4px;
      font-size: 11px;
    }

    .collection-count {
      background: #000000;
      color: white;
      padding: 2px 8px;
      border-radius: 10px;
      font-size: 11px;
      font-weight: 600;
    }

    /* Action Tabs */
    .section {
      margin-bottom: 18px;
    }

    .section-title {
      font-size: 13px;
      font-weight: 600;
      color: #333;
      margin-bottom: 10px;
    }



    .branch-tag {
      display: inline-block;
      background: #28a745;
      color: white;
      font-size: 9px;
      font-weight: 700;
      padding: 2px 6px;
      border-radius: 3px;
      margin-left: 8px;
      position: relative;
      top: -2px;
    }

    .form-textarea {
      resize: vertical;
      min-height: 70px;
      max-height: 200px; /* Prevent textarea from becoming too large */
      width: 100%;
      box-sizing: border-box;
      padding: 12px 16px;
      border: 2px solid #e1e5e9;
      border-radius: 8px;
      font-size: 14px;
      line-height: 20px;
      font-family: inherit;
      transition: border-color 150ms ease;
    }

    .form-textarea:focus {
      outline: none;
      border-color: var(--color-primary-light);
    }

    .form-row {
      display: flex;
      gap: 10px;
    }

    .form-row .form-group {
      flex: 1;
      position: relative;
    }

    /* PR Fields - Hidden by default for push-to-branch */
    .pr-only {
      display: none;
    }

    .pr-only.visible {
      display: block;
    }

    /* Sticky footer layout */
    .main-content {
      padding-bottom: 160px; /* Increased space for sticky footer + expanded textarea */
    }

    .sticky-footer {
      position: fixed;
      bottom: 0;
      left: 0;
      right: 0;
      background: white;
      border-top: 1px solid var(--color-border);
      padding: 16px 20px;
      z-index: 1000;
      box-shadow: 0 -4px 12px rgba(0, 0, 0, 0.1);
    }

    /* Actions */
    .actions {
      display: flex;
      justify-content: center;
      gap: 10px;
      padding: 0; /* Remove padding since it's now in sticky footer */
      background: transparent;
      border-top: 1px solid #e9ecef;
      flex-shrink: 0;
    }

    .btn {
      flex: 1;
      padding: 12px;
      border: none;
      border-radius: 8px;
      font-weight: 500;
      font-size: 14px;
      cursor: pointer;
      transition: all 0.2s;
    }

    .btn-cancel {
      background: #1A1C1E;
      color: white;
    }

    .btn-cancel:hover {
      background: #404347;
      color: white;
    }

    .btn-cancel:focus {
      outline: 2px solid #1A1C1E;
      outline-offset: 2px;
    }

    .btn-submit {
      background: #DEE3FC;
      color: var(--color-text-primary);
      font-weight: 600;
    }

    .btn-submit:hover {
      background: #7C2D92;
      color: white;
    }

    .btn-submit:focus {
      outline: 2px solid var(--color-primary-light);
      outline-offset: 2px;
    }

    /* CI/CD Tooltip Styles */

    /* Information icon styling */
    .learn-more {
      display: inline-flex;
      align-items: center;
      vertical-align: middle;
      transition: transform 0.2s ease, opacity 0.2s ease;
    }

    .learn-more:hover {
      transform: scale(1.1);
    }

    .learn-more i {
      transition: all 0.2s ease;
      padding: 4px;
      border-radius: 50%;
    }

    .learn-more:hover i {
      color: white !important;
      background-color: #C084FC !important;
    }

    /* Missing styles for ds-action-tabs section */
    .ds-action-tabs {
      display: flex;
      gap: 12px;
      margin-bottom: 20px;
    }

    .ds-action-tab {
      flex: 1;
      padding: 16px;
      border: 2px solid #e9ecef;
      border-radius: 8px;
      cursor: pointer;
      transition: all 0.2s;
      text-align: center;
      background: white;
    }

    .ds-action-tab:hover {
      border-color: #DEE3FC;
      background: #f8f9fa;
    }

    .ds-action-tab.active {
      border-color: var(--color-primary);
      background: linear-gradient(135deg, rgba(222, 227, 252, 0.5) 0%, rgba(247, 227, 227, 0.5) 100%);
    }

    .ds-action-tab-title {
      font-size: 14px;
      font-weight: 600;
      color: #333;
      margin-bottom: 4px;
    }

    .ds-action-tab-description {
      font-size: 12px;
      color: #666;
    }

    /* Form Styling */
    .ds-form-group {
      margin-bottom: 16px;
    }

    .ds-form-label {
      display: block;
      font-size: 14px;
      font-weight: 500;
      color: #333;
      margin-bottom: 6px;
    }

    .ds-input {
      width: 100%;
      padding: 12px 16px;
      border: 2px solid #e1e5e9;
      border-radius: 8px;
      font-size: 14px;
      line-height: 20px;
      background: #fff;
      transition: border-color 150ms ease;
      font-family: inherit;
    }

    .ds-input:focus {
      outline: none;
      border-color: #6366f1;
    }

    .ds-input:disabled {
      background: #f9fafb;
      color: #6b7280;
      cursor: not-allowed;
    }

    select.ds-input {
      cursor: pointer;
      padding-right: 40px;
      background-image: url("data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3e%3cpath d='M6 9l6 6 6-6'/%3e%3c/svg%3e");
      background-repeat: no-repeat;
      background-position: right 12px center;
      background-size: 16px;
      appearance: none;
      -webkit-appearance: none;
      -moz-appearance: none;
    }

    /* Branch Configuration */
    .branch-config-push,
    .branch-config-pr {
      margin-top: 12px;
    }

    /* Actions Container */
    .actions {
      display: flex;
      gap: 12px;
      justify-content: center;
      padding: 16px 20px;
      border-top: 1px solid #e5e7eb;
      margin-top: 8px;
      background: #fafbfc;
    }

    /* Vertical Branch Layout - All elements stack vertically */
    .branch-config-push .ds-form-group {
      margin-bottom: 16px;
    }

    .branch-config-push .ds-form-group:last-child {
      margin-bottom: 0;
    }

    /* Disabled Tab Styles */
    .ds-action-tab.disabled {
      opacity: 0.5;
      cursor: not-allowed;
      pointer-events: auto;
      position: relative;
    }

    .ds-action-tab.disabled:hover {
      background: #f5f5f5;
      border-color: #ddd;
      transform: none;
    }

    .ds-action-tab.disabled .ds-action-tab-title,
    .ds-action-tab.disabled .ds-action-tab-description {
      color: #999;
    }

    /* Simple Tooltip for Disabled Elements */
    .ds-action-tab.disabled[data-tooltip]:hover::before {
      content: attr(data-tooltip);
      position: absolute;
      top: -30px;
      left: 50%;
      transform: translateX(-50%);
      background-color: #333;
      color: white;
      padding: 4px 8px;
      border-radius: 4px;
      font-size: 12px;
      white-space: nowrap;
      z-index: 1000;
      pointer-events: none;
    }

    .ds-action-tab.disabled[data-tooltip]:hover::after {
      content: '';
      position: absolute;
      top: -6px;
      left: 50%;
      transform: translateX(-50%);
      border: 4px solid transparent;
      border-top-color: #333;
      z-index: 1000;
      pointer-events: none;
    }

    /* Modal Overlay Styles */
    .ds-tooltip-overlay {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background-color: rgba(0, 0, 0, 0.5);
      z-index: 9999;
      opacity: 0;
      visibility: hidden;
      pointer-events: none;
      transition: all 200ms ease;
    }

    .ds-tooltip-overlay.visible {
      opacity: 1;
      visibility: visible;
      pointer-events: auto;
    }

    .ds-tooltip-popup {
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%) scale(0.9);
      background: white;
      border-radius: 12px;
      box-shadow: 0 20px 40px rgba(0, 0, 0, 0.15);
      max-width: 400px;
      width: 90%;
      max-height: 90vh;
      height: auto;
      overflow: visible;
      z-index: 10000;
      opacity: 0;
      pointer-events: none;
      transition: all 200ms ease;
    }

    .ds-tooltip-popup.visible {
      opacity: 1;
      transform: translate(-50%, -50%) scale(1);
      pointer-events: auto;
    }

    .ds-tooltip-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 20px 20px 16px 20px;
      border-bottom: 1px solid #eee;
    }

    .ds-tooltip-title {
      margin: 0;
      font-size: 18px;
      font-weight: 600;
      color: #333;
    }

    .ds-tooltip-close {
      background: none;
      border: none;
      font-size: 24px;
      color: #999;
      cursor: pointer;
      padding: 4px;
      border-radius: 4px;
      transition: all 150ms ease;
    }

    .ds-tooltip-close:hover {
      background: #f8f9fa;
      color: #333;
    }

    .ds-tooltip-content {
      padding: 0 20px 20px 20px;
      color: #555;
      line-height: 1.5;
      overflow: visible;
      max-height: none;
    }

  </style>
</head>
<body>
  <div class="container main-content">
    <!-- Header -->
    <div class="header">
      <h1><i class="ph-rocket-launch" data-weight="duotone"></i> Push Tokens to GitHub</h1>
    </div>

    <!-- Content -->
    <div class="content">
      <!-- Compact Stats -->
      <div class="stats">
        <div class="stat">
          <div class="stat-value">${tokenData.tokens.length}</div>
          <div class="stat-label">Tokens</div>
        </div>
        <div class="stat">
          <div class="stat-value">${tokenData.variables.length}</div>
          <div class="stat-label">Variables</div>
        </div>
        <div class="stat">
          <div class="stat-value">${collections.length}</div>
          <div class="stat-label">Collections</div>
        </div>
      </div>

      <!-- Collections - Collapsed by Default -->
      ${collections.length > 0 ? `
        <div class="collections">
          <div class="collections-toggle" onclick="toggleCollections()">
            <span class="toggle-icon" id="toggle-icon">▶</span>
            <span class="toggle-text">Collections (${collections.length})</span>
          </div>
          <div class="collections-list" id="collections-list">
            ${collections.map(col => {
              const tokenCount = col.variables?.length || 0;
              return `<div class="collection-item">
                <span>${col.name}</span>
                <span class="collection-count">${tokenCount}</span>
              </div>`;
            }).join('')}
          </div>
        </div>
      ` : ''}

      <!-- Action Selection -->
      <div class="section">
        <div class="section-title">Choose Action</div>
        <div class="ds-action-tabs">
          <div class="ds-action-tab active" id="tab-branch" onclick="selectAction('push-to-branch')">
            <div class="ds-action-tab-title">Push to Branch</div>
            <div class="ds-action-tab-description">Commit to branch</div>
          </div>
          <div class="ds-action-tab disabled" id="tab-pr" data-tooltip="Future Feature">
            <div class="ds-action-tab-title">Create Pull Request</div>
            <div class="ds-action-tab-description">Create PR with review</div>
          </div>
        </div>
      </div>

      <!-- Branch Configuration -->
      <div class="section">
        <div class="section-title">Branch</div>

        <!-- Push to Branch: Vertical Layout -->
        <div class="branch-config-push" id="branch-config-push">
          <!-- Branch Selection Dropdown -->
          <div class="ds-form-group">
            <label class="ds-form-label">Select Branch</label>
            <select class="ds-input" id="branch-select">
              ${this.options.availableBranches && this.options.availableBranches.length > 0 ?
                this.options.availableBranches.map(branch =>
                  `<option value="${branch}" ${branch === defaultBranch ? 'selected' : ''}>${branch}</option>`
                ).join('') :
                `<option value="${defaultBranch}">${defaultBranch}</option>`
              }
            </select>
          </div>

          <!-- Create New Branch Section -->
          <div class="create-branch-section" style="background: #F8F9FA; padding: 8px; border-radius: 8px; margin-top: 4px;">
            <!-- Create New Branch Checkbox -->
            <div class="ds-form-group" style="margin-bottom: 0;">
              <label class="ds-checkbox-label">
                <input
                  type="checkbox"
                  class="ds-checkbox"
                  id="create-new-branch-checkbox"
                  onchange="
                    const newInput = document.getElementById('new-branch-input');
                    const branchDropdown = document.getElementById('branch-select');
                    if (this.checked) {
                      newInput.style.display = 'block';
                      branchDropdown.disabled = true;
                      branchDropdown.style.opacity = '0.5';
                      branchDropdown.style.cursor = 'not-allowed';
                      branchDropdown.style.padding = '3px 4px';
                    } else {
                      newInput.style.display = 'none';
                      branchDropdown.disabled = false;
                      branchDropdown.style.opacity = '1';
                      branchDropdown.style.cursor = 'pointer';
                      branchDropdown.style.padding = '';
                    }"
                >
                <span>Create new branch instead</span>
              </label>
            </div>

            <!-- New Branch Name Input (Hidden by Default) -->
            <div class="ds-form-group" id="new-branch-input" style="display: none;">
              <label class="ds-form-label" style="font-size: 12px;">New Branch Name</label>
              <input
                type="text"
                class="ds-input"
                id="new-branch-name"
                placeholder="feature/update-tokens"
                style="font-size: 11px; height: 32px; padding: 3px 6px;"
              >
              <div class="ds-form-help" style="font-size: 11px;">Enter a name for your new branch</div>
            </div>
          </div>
        </div>

        <!-- Create PR: Two Field Layout (Future Feature - Hidden) -->
        <div class="branch-config-pr" id="branch-config-pr" style="display: none;">
          <div class="ds-form-group">
            <label class="ds-form-label">From Branch (Your Feature Branch)</label>
            <input
              type="text"
              class="ds-input"
              id="from-branch"
              value="${this.prDetails.branchName}"
              placeholder="feature/update-tokens"
            >
            <div class="ds-form-help">The branch where your changes are</div>
          </div>
          <div class="ds-form-group" style="margin-top: 16px;">
            <label class="ds-form-label">To Branch (Base Branch)</label>
            <select class="ds-input" id="to-branch">
              ${this.options.availableBranches && this.options.availableBranches.length > 0 ?
                this.options.availableBranches.map(branch =>
                  `<option value="${branch}" ${branch === defaultBranch ? 'selected' : ''}>${branch}</option>`
                ).join('') :
                `<option value="${defaultBranch}">${defaultBranch}</option>`
              }
            </select>
          </div>
        </div>
      </div>

      <!-- Token File Location (Optional) -->
      <div class="section">
        <div class="ds-form-group">
          <label class="ds-form-label" for="token-file-location">Token File Location (Optional)</label>
          <input
            type="text"
            class="ds-input"
            id="token-file-location"
            value="${savedTokenFileLocation}"
            placeholder="leave empty for root level"
          >
          <div class="ds-form-help">Folder path in your repository (empty = root level)</div>
        </div>
      </div>

      <!-- Commit Message -->
      <div class="section">
        <div class="section-title">Commit Message</div>
        <textarea
          class="form-textarea"
          id="commit-message"
          placeholder="Update design tokens from Figma - 2024-12-30 14:23..."
        >${this.prDetails.commitMessage}</textarea>
        <div class="ds-form-help">Autogenerated commit message with latest changes, write your own if you prefer</div>
      </div>

      <!-- PR-Only Fields -->
      <div class="pr-only" id="pr-fields">
        <div class="section">
          <div class="section-title">Pull Request</div>
          <div class="ds-form-group">
            <label class="ds-form-label">PR Title</label>
            <input
              type="text"
              class="ds-form-input"
              id="pr-title"
              value="${this.prDetails.prTitle}"
              placeholder="Update design tokens"
            >
          </div>
        </div>
      </div>

      <!-- Workflow Trigger Section -->
      <div class="section" style="margin-top: 16px; display: none;">
        <div class="form-group" style="display: flex; align-items: center; gap: 8px;">
          <label class="ds-checkbox-label" style="margin: 0;">
            <input
              type="checkbox"
              class="ds-checkbox"
              id="enable-workflow-trigger"
              ${workflowSettings.workflowTriggerEnabled ? 'checked' : ''}
            >
            <span>Trigger CI/CD workflow after push</span>
          </label>
          <span class="ds-info-icon" data-tooltip="Click for more info" onclick="showCICDTooltip();"><i class="ph-info" data-weight="fill"></i></span>
        </div>

        <div id="workflow-config" style="display: ${workflowSettings.workflowTriggerEnabled ? 'block' : 'none'}; margin-left: 24px; margin-top: 12px;">
          <div class="ds-form-group">
            <label class="ds-form-label">Workflow file name</label>
            <input
              type="text"
              class="ds-form-input"
              id="workflow-filename"
              value="${workflowSettings.workflowFileName}"
              placeholder="transform-tokens.yml"
            >
            <div class="ds-form-help">
              File must exist in <code>.github/workflows/</code>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Sticky Footer for Actions -->
  <div class="sticky-footer">
    <div class="actions">
      <button class="ds-btn ds-btn-secondary" onclick="handleCancel()">← Go Back</button>
      <button class="ds-btn ds-btn-primary" id="submit-btn" onclick="handleSubmit()">Push to Branch</button>
    </div>
  </div>

  <script>
    let currentAction = 'push-to-branch';
    let isNewBranch = true;  // Default, but will be updated based on initial selection

    function toggleCollections() {
      const list = document.getElementById('collections-list');
      const icon = document.getElementById('toggle-icon');
      const isOpen = list.classList.contains('open');

      if (isOpen) {
        list.classList.remove('open');
        icon.classList.remove('open');
      } else {
        list.classList.add('open');
        icon.classList.add('open');
      }
    }

    // Handle base branch selection
    document.addEventListener('DOMContentLoaded', function() {
      const baseBranchSelect = document.getElementById('base-branch');
      const branchNameInput = document.getElementById('branch-name');
      const newTag = document.getElementById('new-tag');

      baseBranchSelect.addEventListener('change', function() {
        if (this.value === '__create_new__') {
          // User wants to create a new branch
          isNewBranch = true;
          newTag.style.display = 'inline-block';
          branchNameInput.disabled = false;
          branchNameInput.value = branchNameInput.getAttribute('data-original-value') || '';
          branchNameInput.focus();
        } else {
          // User selected an existing branch - auto-fill and disable
          isNewBranch = false;
          newTag.style.display = 'none';
          branchNameInput.value = this.value;
          branchNameInput.disabled = true;
        }
      });

      // Initialize the branch name input state based on initial selection
      if (baseBranchSelect.value !== '__create_new__') {
        branchNameInput.value = baseBranchSelect.value;
        branchNameInput.disabled = true;
      }

      // Store original value for when user switches back to create new
      branchNameInput.setAttribute('data-original-value', branchNameInput.value);

      // Check if page has loaded completely

      // Handle create new branch checkbox
      const createNewBranchCheckbox = document.getElementById('create-new-branch-checkbox');
      const newBranchInput = document.getElementById('new-branch-input');


      if (createNewBranchCheckbox && newBranchInput) {
        createNewBranchCheckbox.addEventListener('change', function() {

          const branchDropdown = document.getElementById('branch-select');

          if (this.checked) {
            newBranchInput.style.display = 'block';

            // Disable and style dropdown
            if (branchDropdown) {
              branchDropdown.disabled = true;
              branchDropdown.style.opacity = '0.5';
              branchDropdown.style.cursor = 'not-allowed';
              branchDropdown.style.padding = '3px 4px';
            }

            const nameInput = document.getElementById('new-branch-name');
            if (nameInput) {
              setTimeout(() => nameInput.focus(), 100);
            }
          } else {
            newBranchInput.style.display = 'none';

            // Re-enable and style dropdown
            if (branchDropdown) {
              branchDropdown.disabled = false;
              branchDropdown.style.opacity = '1';
              branchDropdown.style.cursor = 'pointer';
              branchDropdown.style.padding = '';
            }

            const nameInput = document.getElementById('new-branch-name');
            if (nameInput) {
              nameInput.value = '';
            }
          }
        });
      } else {
        console.error('❌ Could not find checkbox elements:', {
          createNewBranchCheckbox: !!createNewBranchCheckbox,
          newBranchInput: !!newBranchInput
        });
      }

      // Handle workflow trigger checkbox
      const workflowCheckbox = document.getElementById('enable-workflow-trigger');
      const workflowConfig = document.getElementById('workflow-config');

      workflowCheckbox.addEventListener('change', function() {
        if (this.checked) {
          workflowConfig.style.display = 'block';
        } else {
          workflowConfig.style.display = 'none';
        }
      });
    });

    function selectAction(action) {
      // Prevent selection of disabled PR option
      if (action === 'create-pr') {
        return;
      }

      currentAction = action;

      // Update tabs
      const branchTab = document.getElementById('tab-branch');
      const prTab = document.getElementById('tab-pr');
      const prFields = document.getElementById('pr-fields');
      const submitBtn = document.getElementById('submit-btn');

      branchTab.classList.remove('active');
      prTab.classList.remove('active');

      if (action === 'push-to-branch') {
        branchTab.classList.add('active');
        prFields.classList.remove('visible');
        submitBtn.textContent = 'Push to Branch';
      }
    }

    function handleCancel() {
      parent.postMessage({ pluginMessage: { type: 'pr-workflow-cancel' } }, '*');
    }

    function handleSubmit() {
      // Get branch information from new structure
      const branchSelect = document.getElementById('branch-select');
      const createNewBranchCheckbox = document.getElementById('create-new-branch-checkbox');
      let branchName, baseBranch, isNewBranch;

      if (createNewBranchCheckbox.checked) {
        // Creating new branch
        branchName = document.getElementById('new-branch-name').value.trim();
        baseBranch = 'main'; // Default base for new branches
        isNewBranch = true;
      } else {
        // Using existing branch
        branchName = branchSelect.value;
        baseBranch = branchSelect.value; // Same as branch name for direct push
        isNewBranch = false;
      }

      // Get workflow trigger config
      const workflowEnabled = document.getElementById('enable-workflow-trigger').checked;
      const workflowFileName = document.getElementById('workflow-filename').value.trim();

      // Get token file location
      const tokenFileLocationElement = document.getElementById('token-file-location');
      const tokenFileLocationRaw = tokenFileLocationElement ? tokenFileLocationElement.value : '';
      const tokenFileLocationValue = tokenFileLocationRaw.trim();
      const tokenFileLocation = tokenFileLocationValue; // Keep empty string as is to allow root placement

      // Save user's choice for next session
      try {
        localStorage.setItem('tokenFileLocation', tokenFileLocation);
      } catch (e) {
        // Silently fail if localStorage unavailable
      }

      const details = {
        action: currentAction,
        branchName: branchName,
        baseBranch: baseBranch,
        commitMessage: document.getElementById('commit-message').value.trim(),
        prTitle: '', // Not used for push-to-branch
        isNewBranch: isNewBranch,
        tokenFileLocation: tokenFileLocation,
        workflowTrigger: workflowEnabled ? {
          enabled: true,
          workflowFileName: workflowFileName || 'transform-tokens.yml'
        } : undefined
      };

      // Validation
      if (!details.branchName) {
        alert('Please enter a branch name');
        return;
      }

      if (!details.commitMessage) {
        alert('Please enter a commit message');
        return;
      }

      if (currentAction === 'create-pr' && !details.prTitle) {
        alert('Please enter a PR title');
        return;
      }

      if (workflowEnabled && !workflowFileName) {
        alert('Please enter a workflow file name');
        return;
      }

      parent.postMessage({
        pluginMessage: {
          type: 'pr-workflow-submit',
          details
        }
      }, '*');
    }

    // CI/CD Tooltip functions
    function showCICDTooltip() {
      const overlay = document.getElementById('cicd-tooltip-overlay');
      const tooltip = document.getElementById('cicd-tooltip');
      if (overlay && tooltip) {
        overlay.classList.add('visible');
        tooltip.classList.add('visible');
      } else {
      }
    }

    function hideCICDTooltip() {
      const overlay = document.getElementById('cicd-tooltip-overlay');
      const tooltip = document.getElementById('cicd-tooltip');
      if (overlay && tooltip) {
        overlay.classList.remove('visible');
        tooltip.classList.remove('visible');
      }
    }

    window.showCICDTooltip = showCICDTooltip;
    window.hideCICDTooltip = hideCICDTooltip;

    // Initialize isNewBranch based on the currently selected branch
    function initializeBranchState() {
      const baseBranchSelect = document.getElementById('base-branch');
      const branchNameInput = document.getElementById('branch-name');
      const newTag = document.getElementById('new-tag');

      if (baseBranchSelect && branchNameInput) {
        const selectedValue = baseBranchSelect.value;
        if (selectedValue === '__create_new__') {
          isNewBranch = true;
          newTag.style.display = 'inline-block';
          branchNameInput.disabled = false;
        } else {
          // User has selected an existing branch
          isNewBranch = false;
          newTag.style.display = 'none';
          branchNameInput.value = selectedValue;
          branchNameInput.disabled = true;
        }
      }
    }

    // Initialize when the page loads
    document.addEventListener('DOMContentLoaded', initializeBranchState);

    // Also initialize immediately in case DOM is already ready
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', initializeBranchState);
    } else {
      initializeBranchState();
    }
  </script>

  <!-- CI/CD Workflow Tooltip -->
  <div class="ds-tooltip-overlay" id="cicd-tooltip-overlay" onclick="hideCICDTooltip()"></div>
  <div class="ds-tooltip-popup" id="cicd-tooltip">
    <div class="ds-tooltip-header">
      <h3 class="ds-tooltip-title">⚙️ What does this do?</h3>
      <button class="ds-tooltip-close" onclick="hideCICDTooltip()" aria-label="Close">×</button>
    </div>
    <div class="ds-tooltip-content">
      <p><strong>In simple terms:</strong></p>
      <p>After you push your design tokens to GitHub, this feature automatically tells GitHub to "run the build process."</p>

      <p style="margin-top: 12px;"><strong>What happens when enabled?</strong></p>
      <ul>
        <li>Your tokens get automatically converted into developer-friendly code</li>
        <li>Developers get notified that new tokens are ready to use</li>
        <li>Quality checks run automatically to catch any issues</li>
      </ul>

      <p style="margin-top: 12px;"><strong>When should I enable this?</strong></p>
      <p>Enable if your development team has set up automation in GitHub. Ask your developer team if you're unsure!</p>

      <p style="margin-top: 12px; padding: 12px; background: #f0f9ff; border-radius: 6px; border-left: 3px solid #0ea5e9; font-size: 12px;">
        <strong>💡 Not sure?</strong> You can leave this unchecked. Developers can manually process tokens later if needed.
      </p>
    </div>
  </div>
</body>
</html>`;

    figma.showUI(html, getWindowOptions('Push Tokens to GitHub'));
  }

  // =============================================================================
  // SUCCESS MODAL
  // =============================================================================

  /**
   * Show success modal with result
   */
  private showSuccessModal(success: PRSuccess): void {
    const isPR = success.action === 'create-pr';

    const html = `
<!DOCTYPE html>
<html>
<head>
  <link href="https://unpkg.com/phosphor-icons@1.4.2/src/css/icons.css" rel="stylesheet">
  ${this.getSharedStyles()}
  <style>
    /* Body background with design system gradient */
    body {
      background: var(--color-background-gradient) !important;
      margin: 0;
      padding: 24px;
      min-height: 100vh;
      font-family: var(--font-family);
    }

    .container {
      padding: 40px 30px;
      text-align: center;
    }

    .icon {
      font-size: 64px;
      margin-bottom: 20px;
    }

    .title {
      font-size: 24px;
      font-weight: 600;
      color: var(--color-text-primary);
      margin-bottom: 8px;
    }

    .subtitle {
      color: #1A1C1E;
      margin-bottom: 30px;
    }

    .details {
      background: var(--color-background-secondary);
      border-radius: 8px;
      padding: 12px 16px;
      margin-bottom: 16px;
      text-align: left;
    }

    .detail-row {
      display: flex;
      justify-content: space-between;
      padding: 6px 0;
      border-bottom: 1px solid var(--color-border);
    }

    .detail-row:last-child {
      border-bottom: none;
    }

    .detail-label {
      font-weight: 500;
      color: var(--color-text-tertiary);
      font-size: 13px;
    }

    .detail-value {
      font-weight: 600;
      color: var(--color-text-primary);
      font-size: 13px;
    }

    .link-btn {
      display: block;
      background: var(--color-primary-300);
      color: var(--color-text-primary);
      text-decoration: none;
      padding: 12px 16px;
      border-radius: 8px;
      font-weight: 600;
      margin-bottom: 16px;
      transition: all 0.2s;
      text-align: center;
    }

    .link-btn:hover {
      background: var(--color-primary);
      color: white;
      transform: translateY(-1px);
    }

    .link-btn:focus {
      outline: 2px solid var(--color-primary-light);
      outline-offset: 2px;
    }

    /* Using design system button styles without overrides */
  </style>
</head>
<body>
  <div class="container">
    <div class="icon"><i class="ph-rocket-launch" data-weight="fill" style="color: var(--color-mint-700);"></i></div>
    <h1 class="title">${isPR ? 'Pull Request Created!' : 'Pushed to Branch!'}</h1>
    <p class="subtitle">${isPR ? 'Your tokens are ready for review' : 'Your Tokens are now ready to be consumed!'}</p>

    <div class="details">
      ${isPR && success.prNumber ? `
        <div class="detail-row">
          <span class="detail-label">PR Number</span>
          <span class="detail-value">#${success.prNumber}</span>
        </div>
      ` : ''}
      <div class="detail-row">
        <span class="detail-label">Branch</span>
        <span class="detail-value">${success.branchName}</span>
      </div>
      ${success.workflowTrigger?.triggered ? `
        <div class="detail-row">
          <span class="detail-label">Workflow</span>
          <span class="detail-value" style="color: ${success.workflowTrigger.success ? 'var(--color-success)' : 'var(--color-error)'}">
            ${success.workflowTrigger.success ? '<i class="ph-check" data-weight="bold" style="color: #16a34a;"></i> Triggered' : '<i class="ph-warning" data-weight="fill" style="color: #d97706;"></i> Failed'}
          </span>
        </div>
      ` : ''}
    </div>

    ${success.workflowTrigger?.triggered && !success.workflowTrigger.success ? `
      <div style="background: var(--color-warning-light); border-left: 4px solid var(--color-warning); padding: 12px; margin-bottom: 16px; text-align: left; border-radius: 4px;">
        <div style="font-weight: 600; color: var(--color-warning-dark); margin-bottom: 4px;">Workflow Trigger Warning</div>
        <div style="font-size: 12px; color: var(--color-warning-dark);">${success.workflowTrigger.error || 'Failed to trigger workflow'}</div>
      </div>
    ` : ''}

    ${success.prUrl ? `
      <a href="${success.prUrl}" class="link-btn" target="_blank">
        <i class="ph-link" data-weight="bold"></i> View ${isPR ? 'Pull Request' : 'Branch'} on GitHub
      </a>
    ` : ''}

    ${success.workflowTrigger?.success && success.workflowTrigger.workflowUrl ? `
      <a href="${success.workflowTrigger.workflowUrl}" class="link-btn" target="_blank" style="background: var(--color-info-light);">
        <i class="ph-rocket-launch" data-weight="bold"></i> View Workflow Actions
      </a>
    ` : ''}

    <button class="ds-btn ds-btn-secondary-filled" onclick="handleDone()">Done</button>
  </div>

  <script>
    function handleDone() {
      parent.postMessage({ pluginMessage: { type: 'pr-workflow-done' } }, '*');
    }
  </script>
</body>
</html>`;

    figma.showUI(html, getWindowOptions('Success'));
  }

  // =============================================================================
  // MESSAGE HANDLING
  // =============================================================================

  /**
   * Setup message handling from UI
   */
  private setupMessageHandling(): void {
    figma.ui.onmessage = async (msg) => {
      switch (msg.type) {
        case 'pr-workflow-cancel':
          this.options.onCancel();
          break;

        case 'pr-workflow-submit':
          const details: PRDetails = {
            action: msg.details.action,
            branchName: msg.details.branchName,
            commitMessage: msg.details.commitMessage,
            prTitle: msg.details.prTitle,
            prBody: this.generatePRBody(),
            isNewBranch: msg.details.isNewBranch,
            tokenFileLocation: msg.details.tokenFileLocation,  // NEW: Include token file location
            workflowTrigger: msg.details.workflowTrigger  // NEW: Include workflow trigger config
          };

          // Save workflow settings for next time
          if (msg.details.workflowTrigger) {
            await SecureStorage.storeWorkflowSettings({
              workflowTriggerEnabled: msg.details.workflowTrigger.enabled,
              workflowFileName: msg.details.workflowTrigger.workflowFileName
            });
          }

          this.options.onComplete(details);
          break;

        case 'pr-workflow-done':
          figma.closePlugin();
          break;
      }
    };
  }

  // =============================================================================
  // UTILITY METHODS
  // =============================================================================

  /**
   * Get shared CSS styles
   */
  private getSharedStyles(): string {
    return `<style>${generateDesignSystemCSS()}</style>`;
  }
}
