/**
 * Pull Request Workflow UI
 *
 * Single-step workflow for pushing tokens to GitHub.
 * User can choose: Push to Branch OR Create Pull Request
 */

import { ExtractionResult } from '../TokenExtractor';

// =============================================================================
// TYPES
// =============================================================================

export interface PRWorkflowOptions {
  tokenData: ExtractionResult;
  defaultBranch?: string;
  availableBranches?: string[];
  onComplete: (details: PRDetails) => void;
  onCancel: () => void;
}

export interface PRDetails {
  action: 'push-to-branch' | 'create-pr';
  branchName: string;
  commitMessage: string;
  prTitle?: string;
  prBody?: string;
  isNewBranch: boolean;
}

export interface PRSuccess {
  prNumber?: number;
  prUrl?: string;
  branchName: string;
  action: 'push-to-branch' | 'create-pr';
}

// =============================================================================
// PR WORKFLOW UI
// =============================================================================

export class PRWorkflowUI {
  private options: PRWorkflowOptions;
  private prDetails: Partial<PRDetails> = {};

  constructor(options: PRWorkflowOptions) {
    this.options = options;
    this.initializePRDetails();
  }

  /**
   * Show the unified workflow
   */
  show(): void {
    this.showUnifiedModal();
    this.setupMessageHandling();
  }

  /**
   * Show success modal after operation
   */
  showSuccess(success: PRSuccess): void {
    this.showSuccessModal(success);
  }

  // =============================================================================
  // INITIALIZATION
  // =============================================================================

  /**
   * Initialize PR details with defaults
   */
  private initializePRDetails(): void {
    const timestamp = new Date().toISOString()
      .replace(/:/g, '-')
      .replace(/\..+/, '')
      .replace('T', '-');

    this.prDetails = {
      action: 'create-pr',
      branchName: `tokens/update-${timestamp}`,
      commitMessage: 'Update design tokens from Figma',
      prTitle: `Update design tokens - ${new Date().toLocaleDateString()}`,
      prBody: this.generatePRBody(),
      isNewBranch: true
    };
  }

  /**
   * Generate PR body markdown
   */
  private generatePRBody(): string {
    const { tokenData } = this.options;
    const date = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    return `## Design Token Update

**Exported from Figma**: ${tokenData.metadata.documentName || 'Figma Document'}
**Date**: ${date}

### File Changes
- \`tokens/raw/figma-tokens.json\`

### Review Checklist
- [ ] Token values are correct
- [ ] No breaking changes to token names
- [ ] Ready to merge

---
🤖 Generated by Figma Design System Distributor`;
  }

  // =============================================================================
  // UNIFIED MODAL
  // =============================================================================

  /**
   * Show unified single-step modal
   */
  private showUnifiedModal(): void {
    const { tokenData } = this.options;
    const collections = tokenData.collections || [];
    const defaultBranch = this.options.defaultBranch || 'main';

    const html = `
<!DOCTYPE html>
<html>
<head>
  ${this.getSharedStyles()}
  <style>
    body {
      margin: 0;
      padding: 0;
      overflow: hidden;
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
    }

    .container {
      height: 100vh;
      display: flex;
      flex-direction: column;
      background: white;
    }

    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 16px 20px;
      flex-shrink: 0;
    }

    .header h1 {
      font-size: 18px;
      font-weight: 600;
      margin: 0;
    }

    .content {
      flex: 1;
      overflow-y: auto;
      padding: 20px;
    }

    /* Compact Stats */
    .stats {
      display: flex;
      gap: 12px;
      margin-bottom: 20px;
    }

    .stat {
      flex: 1;
      background: #f8f9fa;
      padding: 10px;
      border-radius: 6px;
      text-align: center;
    }

    .stat-value {
      font-size: 20px;
      font-weight: 600;
      color: #667eea;
      margin-bottom: 2px;
    }

    .stat-label {
      font-size: 10px;
      color: #666;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }

    /* Collections - Collapsed by Default */
    .collections {
      margin-bottom: 20px;
    }

    .collections-toggle {
      display: flex;
      align-items: center;
      gap: 6px;
      padding: 8px;
      cursor: pointer;
      user-select: none;
      border-radius: 4px;
      transition: background 0.2s;
    }

    .collections-toggle:hover {
      background: #f8f9fa;
    }

    .toggle-icon {
      font-size: 10px;
      transition: transform 0.3s;
    }

    .toggle-icon.open {
      transform: rotate(90deg);
    }

    .toggle-text {
      font-size: 11px;
      color: #666;
    }

    .collections-list {
      max-height: 0;
      overflow: hidden;
      transition: max-height 0.3s ease;
    }

    .collections-list.open {
      max-height: 150px;
      overflow-y: auto;
      margin-top: 8px;
    }

    .collection-item {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 6px 10px;
      background: #f8f9fa;
      border-radius: 4px;
      margin-bottom: 4px;
      font-size: 11px;
    }

    .collection-count {
      background: #667eea;
      color: white;
      padding: 2px 8px;
      border-radius: 10px;
      font-size: 10px;
      font-weight: 600;
    }

    /* Action Tabs */
    .section {
      margin-bottom: 18px;
    }

    .section-title {
      font-size: 13px;
      font-weight: 600;
      color: #333;
      margin-bottom: 10px;
    }

    .action-tabs {
      display: flex;
      gap: 10px;
      margin-bottom: 18px;
    }

    .action-tab {
      flex: 1;
      padding: 12px;
      border: 2px solid #e9ecef;
      border-radius: 8px;
      background: white;
      cursor: pointer;
      transition: all 0.2s;
      text-align: center;
    }

    .action-tab:hover {
      border-color: #667eea;
    }

    .action-tab.active {
      border-color: #667eea;
      background: #f0f3ff;
    }

    .tab-title {
      font-weight: 600;
      font-size: 13px;
      color: #333;
      margin-bottom: 2px;
    }

    .tab-desc {
      font-size: 10px;
      color: #666;
    }

    /* Form Fields */
    .form-group {
      margin-bottom: 14px;
    }

    .form-label {
      display: block;
      font-weight: 500;
      font-size: 12px;
      color: #333;
      margin-bottom: 6px;
    }

    .form-input,
    .form-select,
    .form-textarea {
      width: 100%;
      padding: 10px;
      border: 2px solid #e9ecef;
      border-radius: 6px;
      font-size: 13px;
      font-family: inherit;
      transition: border-color 0.2s;
      background: white;
    }

    .form-input:focus,
    .form-select:focus,
    .form-textarea:focus {
      outline: none;
      border-color: #667eea;
    }

    .branch-tag {
      display: inline-block;
      background: #28a745;
      color: white;
      font-size: 9px;
      font-weight: 700;
      padding: 2px 6px;
      border-radius: 3px;
      margin-left: 8px;
      position: relative;
      top: -2px;
    }

    .form-textarea {
      resize: vertical;
      min-height: 70px;
    }

    .form-row {
      display: flex;
      gap: 10px;
    }

    .form-row .form-group {
      flex: 1;
      position: relative;
    }

    /* PR Fields - Hidden by default for push-to-branch */
    .pr-only {
      display: none;
    }

    .pr-only.visible {
      display: block;
    }

    /* Actions */
    .actions {
      display: flex;
      gap: 10px;
      padding: 16px 20px;
      background: #f8f9fa;
      border-top: 1px solid #e9ecef;
      flex-shrink: 0;
    }

    .btn {
      flex: 1;
      padding: 12px;
      border: none;
      border-radius: 8px;
      font-weight: 500;
      font-size: 14px;
      cursor: pointer;
      transition: all 0.2s;
    }

    .btn-cancel {
      background: #6c757d;
      color: white;
    }

    .btn-cancel:hover {
      background: #5a6268;
    }

    .btn-submit {
      background: #667eea;
      color: white;
    }

    .btn-submit:hover {
      background: #5a6fd8;
    }
  </style>
</head>
<body>
  <div class="container">
    <!-- Header -->
    <div class="header">
      <h1>🚀 Push Tokens to GitHub</h1>
    </div>

    <!-- Content -->
    <div class="content">
      <!-- Compact Stats -->
      <div class="stats">
        <div class="stat">
          <div class="stat-value">${tokenData.tokens.length}</div>
          <div class="stat-label">Tokens</div>
        </div>
        <div class="stat">
          <div class="stat-value">${tokenData.variables.length}</div>
          <div class="stat-label">Variables</div>
        </div>
        <div class="stat">
          <div class="stat-value">${collections.length}</div>
          <div class="stat-label">Collections</div>
        </div>
      </div>

      <!-- Collections - Collapsed by Default -->
      ${collections.length > 0 ? `
        <div class="collections">
          <div class="collections-toggle" onclick="toggleCollections()">
            <span class="toggle-icon" id="toggle-icon">▶</span>
            <span class="toggle-text">Collections (${collections.length})</span>
          </div>
          <div class="collections-list" id="collections-list">
            ${collections.map(col => {
              const tokenCount = col.variables?.length || 0;
              return `<div class="collection-item">
                <span>${col.name}</span>
                <span class="collection-count">${tokenCount}</span>
              </div>`;
            }).join('')}
          </div>
        </div>
      ` : ''}

      <!-- Action Selection -->
      <div class="section">
        <div class="section-title">Choose Action</div>
        <div class="action-tabs">
          <div class="action-tab" id="tab-branch" onclick="selectAction('push-to-branch')">
            <div class="tab-title">Push to Branch</div>
            <div class="tab-desc">Commit to branch</div>
          </div>
          <div class="action-tab active" id="tab-pr" onclick="selectAction('create-pr')">
            <div class="tab-title">Create Pull Request</div>
            <div class="tab-desc">Create PR with review</div>
          </div>
        </div>
      </div>

      <!-- Branch Configuration -->
      <div class="section">
        <div class="section-title">Branch</div>
        <div class="form-row">
          <div class="form-group" style="flex: 2;">
            <label class="form-label">Branch Name</label>
            <input
              type="text"
              class="form-input"
              id="branch-name"
              value="${this.prDetails.branchName}"
              placeholder="tokens/update-2025-10-07"
            >
            <span class="branch-tag" id="new-tag" style="display: none;">NEW</span>
          </div>
          <div class="form-group" style="flex: 1;">
            <label class="form-label">Base Branch</label>
            <select class="form-select" id="base-branch">
              ${this.options.availableBranches && this.options.availableBranches.length > 0 ?
                this.options.availableBranches.map(branch =>
                  `<option value="${branch}" ${branch === defaultBranch ? 'selected' : ''}>${branch}</option>`
                ).join('') :
                `<option value="${defaultBranch}">${defaultBranch}</option>`
              }
              <option value="__create_new__">+ Create new branch</option>
            </select>
          </div>
        </div>
      </div>

      <!-- Commit Message -->
      <div class="section">
        <div class="section-title">Commit Message</div>
        <textarea
          class="form-textarea"
          id="commit-message"
          placeholder="Update design tokens from Figma"
        >${this.prDetails.commitMessage}</textarea>
      </div>

      <!-- PR-Only Fields -->
      <div class="pr-only visible" id="pr-fields">
        <div class="section">
          <div class="section-title">Pull Request</div>
          <div class="form-group">
            <label class="form-label">PR Title</label>
            <input
              type="text"
              class="form-input"
              id="pr-title"
              value="${this.prDetails.prTitle}"
              placeholder="Update design tokens"
            >
          </div>
        </div>
      </div>
    </div>

    <!-- Actions -->
    <div class="actions">
      <button class="btn btn-cancel" onclick="handleCancel()">Cancel</button>
      <button class="btn btn-submit" id="submit-btn" onclick="handleSubmit()">Create Pull Request</button>
    </div>
  </div>

  <script>
    let currentAction = 'create-pr';
    let isNewBranch = true;

    function toggleCollections() {
      const list = document.getElementById('collections-list');
      const icon = document.getElementById('toggle-icon');
      const isOpen = list.classList.contains('open');

      if (isOpen) {
        list.classList.remove('open');
        icon.classList.remove('open');
      } else {
        list.classList.add('open');
        icon.classList.add('open');
      }
    }

    // Handle base branch selection
    document.addEventListener('DOMContentLoaded', function() {
      const baseBranchSelect = document.getElementById('base-branch');
      const branchNameInput = document.getElementById('branch-name');
      const newTag = document.getElementById('new-tag');

      baseBranchSelect.addEventListener('change', function() {
        if (this.value === '__create_new__') {
          isNewBranch = true;
          newTag.style.display = 'inline-block';
          branchNameInput.focus();
        } else {
          isNewBranch = false;
          newTag.style.display = 'none';
        }
      });
    });

    function selectAction(action) {
      currentAction = action;

      // Update tabs
      const branchTab = document.getElementById('tab-branch');
      const prTab = document.getElementById('tab-pr');
      const prFields = document.getElementById('pr-fields');
      const submitBtn = document.getElementById('submit-btn');

      branchTab.classList.remove('active');
      prTab.classList.remove('active');

      if (action === 'push-to-branch') {
        branchTab.classList.add('active');
        prFields.classList.remove('visible');
        submitBtn.textContent = 'Push to Branch';
      } else {
        prTab.classList.add('active');
        prFields.classList.add('visible');
        submitBtn.textContent = 'Create Pull Request';
      }
    }

    function handleCancel() {
      parent.postMessage({ pluginMessage: { type: 'pr-workflow-cancel' } }, '*');
    }

    function handleSubmit() {
      const baseBranchValue = document.getElementById('base-branch').value;
      const actualBaseBranch = baseBranchValue === '__create_new__' ? 'main' : baseBranchValue;

      const details = {
        action: currentAction,
        branchName: document.getElementById('branch-name').value.trim(),
        baseBranch: actualBaseBranch,
        commitMessage: document.getElementById('commit-message').value.trim(),
        prTitle: document.getElementById('pr-title').value.trim(),
        isNewBranch: isNewBranch
      };

      // Validation
      if (!details.branchName) {
        alert('Please enter a branch name');
        return;
      }

      if (!details.commitMessage) {
        alert('Please enter a commit message');
        return;
      }

      if (currentAction === 'create-pr' && !details.prTitle) {
        alert('Please enter a PR title');
        return;
      }

      parent.postMessage({
        pluginMessage: {
          type: 'pr-workflow-submit',
          details
        }
      }, '*');
    }
  </script>
</body>
</html>`;

    figma.showUI(html, { width: 600, height: 700, themeColors: true });
  }

  // =============================================================================
  // SUCCESS MODAL
  // =============================================================================

  /**
   * Show success modal with result
   */
  private showSuccessModal(success: PRSuccess): void {
    const isPR = success.action === 'create-pr';

    const html = `
<!DOCTYPE html>
<html>
<head>
  ${this.getSharedStyles()}
  <style>
    .container {
      padding: 40px 30px;
      text-align: center;
    }

    .icon {
      font-size: 64px;
      margin-bottom: 20px;
    }

    .title {
      font-size: 24px;
      font-weight: 600;
      color: #28a745;
      margin-bottom: 8px;
    }

    .subtitle {
      color: #666;
      margin-bottom: 30px;
    }

    .details {
      background: #f8f9fa;
      border-radius: 8px;
      padding: 20px;
      margin-bottom: 20px;
      text-align: left;
    }

    .detail-row {
      display: flex;
      justify-content: space-between;
      padding: 10px 0;
      border-bottom: 1px solid #e9ecef;
    }

    .detail-row:last-child {
      border-bottom: none;
    }

    .detail-label {
      font-weight: 500;
      color: #666;
      font-size: 13px;
    }

    .detail-value {
      font-weight: 600;
      color: #333;
      font-size: 13px;
    }

    .link-btn {
      display: block;
      background: #667eea;
      color: white;
      text-decoration: none;
      padding: 14px;
      border-radius: 8px;
      font-weight: 500;
      margin-bottom: 16px;
      transition: background 0.2s;
    }

    .link-btn:hover {
      background: #5a6fd8;
    }

    .btn-done {
      width: 100%;
      padding: 12px;
      background: #6c757d;
      color: white;
      border: none;
      border-radius: 8px;
      font-weight: 500;
      font-size: 14px;
      cursor: pointer;
      transition: background 0.2s;
    }

    .btn-done:hover {
      background: #5a6268;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="icon">✅</div>
    <h1 class="title">${isPR ? 'Pull Request Created!' : 'Pushed to Branch!'}</h1>
    <p class="subtitle">${isPR ? 'Your tokens are ready for review' : 'Your tokens have been committed'}</p>

    <div class="details">
      ${isPR && success.prNumber ? `
        <div class="detail-row">
          <span class="detail-label">PR Number</span>
          <span class="detail-value">#${success.prNumber}</span>
        </div>
      ` : ''}
      <div class="detail-row">
        <span class="detail-label">Branch</span>
        <span class="detail-value">${success.branchName}</span>
      </div>
    </div>

    ${success.prUrl ? `
      <a href="${success.prUrl}" class="link-btn" target="_blank">
        🔗 View ${isPR ? 'Pull Request' : 'Branch'} on GitHub
      </a>
    ` : ''}

    <button class="btn-done" onclick="handleDone()">Done</button>
  </div>

  <script>
    function handleDone() {
      parent.postMessage({ pluginMessage: { type: 'pr-workflow-done' } }, '*');
    }
  </script>
</body>
</html>`;

    figma.showUI(html, { width: 500, height: 450, themeColors: true });
  }

  // =============================================================================
  // MESSAGE HANDLING
  // =============================================================================

  /**
   * Setup message handling from UI
   */
  private setupMessageHandling(): void {
    figma.ui.onmessage = async (msg) => {
      switch (msg.type) {
        case 'pr-workflow-cancel':
          this.options.onCancel();
          break;

        case 'pr-workflow-submit':
          const details: PRDetails = {
            action: msg.details.action,
            branchName: msg.details.branchName,
            commitMessage: msg.details.commitMessage,
            prTitle: msg.details.prTitle,
            prBody: this.generatePRBody(),
            isNewBranch: msg.details.isNewBranch
          };
          this.options.onComplete(details);
          break;

        case 'pr-workflow-done':
          figma.closePlugin();
          break;
      }
    };
  }

  // =============================================================================
  // UTILITY METHODS
  // =============================================================================

  /**
   * Get shared CSS styles
   */
  private getSharedStyles(): string {
    return `
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }

        body {
          font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
          background: white;
        }
      </style>
    `;
  }
}
